### ISSUE TITLE
Allow json params

### ISSUE THREAD

**Issue by arvigeus** [joewalnes/filtrex#29]
```
const expression = 'answer.index > 1 ? "Yes" : "No"';

const myfilter = filtrex(expression);

// Execute function
console.log(myfilter({ answer: { index: 2 } })); // returns "No"
```

**Comment by cshaa** [comment]
Right now Filtrex takes `.` as a part of the identifier, so this would work:
```javascript
console.log(myfilter({ 'answer.index': 2 })); // returns "Yes"
```
In [my fork](https://github.com/m93a/filtrex/) I've implemented an `of` operator – you'd use it like so:
```javascript
const expression = 'index of answer > 1 ? "Yes" : "No"';

const myfilter = filtrex(expression);

// Execute function
console.log(myfilter({ answer: { index: 2 } })); // returns "Yes"
```

**Comment by cshaa** [comment]
Version 1.0.0 that was published today on the [official NPM](http://npmjs.com/package/filtrex) supports the `of` operator, so you can use that. Would you please close this issue, I don't have moderator rights here 😅
