### ISSUE TITLE
bower.json

### ISSUE THREAD

**Issue by lipis** [joewalnes/filtrex#3]
![687474703a2f2f7777772e6c6976656d656d652e636f6d2f6c3572356f32702e6a7067](https://cloud.githubusercontent.com/assets/125676/2995655/27c90462-dce1-11e3-8915-a462a1e49758.jpg)

(Stolen from: https://github.com/mdo/wtf-forms/issues/5)

**Comment by gajus** [comment]
@joewalnes Where is package.json though?
